### PR TITLE
Fixed error in script description

### PR DESCRIPTION
**Pull request by dimsav**

### CODE REVIEW

**Comment by theophani** [comment]
Hrmm. I’m not at a computer to verify this change. To other repo owners: please verify before merging.

**Comment by xMartin** [comment]
Funny that nobody found that, yet. Thanks! I will also fix it in the German translation.

**Comment by xMartin** [comment]
Will fix ist in the js-beginners-4h-workshop-1 repo, too, as this is what we are really using.

**Comment by xMartin** [comment]
Ok, this had to be fixed in more places:
https://github.com/OpenTechSchool/js-beginners-day1/commit/c021eda78521898fcd8bd58f9a97ae5f193b4bcf
https://github.com/OpenTechSchool/js-beginners-4h-workshop-1/commit/359ff3f9d8ce56cbd86459d2d1d144e95a6c38e8

Done.

**Pull request merged**
